### ISSUE TITLE
seg fault when run on ssh but fine on mac

### ISSUE THREAD

**Issue by gracecuenca** [gracecuenca/tha_swami#2]
issue:
` *** Error in './color': double free or corruption (!prev): 0x00000000012ee010 ***`

**Comment by gracecuenca** [comment]
the error before had to do w/ accessing memory that we weren't supposed to so I tried to fix by allocating mem using malloc. fixed the memory problem, but now the error is w/ freeing something that was already freed ?? not sure where in the code this is happening

**Comment by naotakak** [comment]
fixed, need to free in main bc we use char * screen multiple times
